--[[
	Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	By considering the terms in the Fibonacci sequence whose values do not exceed 
four million, find the sum of the even-valued terms.
]]

local s1, s2 = 0, 1
local s3 = 0
local sum = 0

function fibonacci (size_limit)
		
	while s3 <= size_limit do
		s3 = s1 + s2
		
		if s3 % 2 == 0 then sum = sum + s3 end
		
		if s3 > size_limit then return s2 end

		s1 = s2
		s2 = s3
	end
end	
	
print(fibonacci(4*10^6))
print(sum) -- 4613732.